<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#A-simple-example" data-toc-modified-id="A-simple-example-0.1"><span class="toc-item-num">0.1&nbsp;&nbsp;</span>A simple example</a></span></li><li><span><a href="#Exercise" data-toc-modified-id="Exercise-0.2"><span class="toc-item-num">0.2&nbsp;&nbsp;</span>Exercise</a></span></li></ul></li><li><span><a href="#M-matrices" data-toc-modified-id="M-matrices-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>M-matrices</a></span><ul class="toc-item"><li><span><a href="#Exercise" data-toc-modified-id="Exercise-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Exercise</a></span><ul class="toc-item"><li><span><a href="#An-example" data-toc-modified-id="An-example-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>An example</a></span></li></ul></li><li><span><a href="#Principal-submatrices-minors" data-toc-modified-id="Principal-submatrices-minors-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Principal submatrices minors</a></span><ul class="toc-item"><li><span><a href="#Exercises" data-toc-modified-id="Exercises-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Exercises</a></span></li></ul></li></ul></li><li><span><a href="#SPD-matrices" data-toc-modified-id="SPD-matrices-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>SPD matrices</a></span><ul class="toc-item"><li><span><a href="#Exerise" data-toc-modified-id="Exerise-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Exerise</a></span></li><li><span><a href="#Exercise" data-toc-modified-id="Exercise-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Exercise</a></span></li></ul></li><li><span><a href="#To-finish" data-toc-modified-id="To-finish-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>To finish</a></span></li><li><span><a href="#Part-2:" data-toc-modified-id="Part-2:-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Part 2:</a></span></li></ul></div>

# M-matrices and SPD matrices

**de Brun Summer School, 28 May 2025**

Niall Madden.

In this session, we'll make some practical investigations into M-matrices and SPD matrices.
We'll use `numpy` so will load some modules:

In [41]:
import numpy as np
from numpy.linalg import eigvals, inv, norm, det

### A simple example

In the morning session, had the following example (which I also give as a reminder of how to define a matrix in `numpy`:

In [5]:
A = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]
])

We can see it is a Z-matrix. To check if it is an M-matrix, let's compute the inverse:

In [45]:
A_inv = inv(A)
print("\nInverse of A:\n", A_inv)
print("\nIs A inverse nonnegative?", np.all(A_inv >= 0))


Inverse of A:
 [[0.23076923 0.15384615 0.23076923 0.15384615]
 [0.08791209 0.43956044 0.37362637 0.2967033 ]
 [0.06593407 0.32967033 0.78021978 0.47252747]
 [0.05494505 0.27472527 0.48351648 0.56043956]]

Is A inverse nonnegative? True


Sometimes it is helpful to compute the eigenvalues of a matrix. Do that like this:

In [8]:
eigvals(A)

array([3.41421356, 2.        , 0.58578644])

FYI, these can also be written as $2$, $2-\sqrt{2}$ and $2+\sqrt{2}$.

### Exercise

Give an example of a matrix $B$ and scalar $s$ such that $B \geq 0$, $s \geq \rho(B)$, and $A=sI + B$. Verify that $T = \frac{1}{s}B$ is convergent.

Tip: To make an identity matrix, try `I = np.eye(n)`. To compute the norm of a matrix, try `norm(T)`.

In [9]:
B = np.array([
    [1, 1, 0],
    [1, 1, 1],
    [0, 1, 1]
])

I = np.eye(3)

In [11]:
print(3*I-B)

[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]


In [26]:
T = B/3
print(T)
k=0
while norm(T**k)>0: 
    k+=10
    print(f"k={k:5d} ||T||={norm(T**k):.3e}" )


[[0.33333333 0.33333333 0.        ]
 [0.33333333 0.33333333 0.33333333]
 [0.         0.33333333 0.33333333]]
k=   10 ||T||=4.481e-05
k=   20 ||T||=7.588e-10
k=   30 ||T||=1.285e-14
k=   40 ||T||=2.176e-19
k=   50 ||T||=3.685e-24
k=   60 ||T||=6.241e-29
k=   70 ||T||=1.057e-33
k=   80 ||T||=1.790e-38
k=   90 ||T||=3.031e-43
k=  100 ||T||=5.134e-48
k=  110 ||T||=8.694e-53
k=  120 ||T||=1.472e-57
k=  130 ||T||=2.493e-62
k=  140 ||T||=4.223e-67
k=  150 ||T||=7.151e-72
k=  160 ||T||=1.211e-76
k=  170 ||T||=2.051e-81
k=  180 ||T||=3.473e-86
k=  190 ||T||=5.882e-91
k=  200 ||T||=9.961e-96
k=  210 ||T||=1.687e-100
k=  220 ||T||=2.857e-105
k=  230 ||T||=4.838e-110
k=  240 ||T||=8.193e-115
k=  250 ||T||=1.388e-119
k=  260 ||T||=2.350e-124
k=  270 ||T||=3.979e-129
k=  280 ||T||=6.739e-134
k=  290 ||T||=1.141e-138
k=  300 ||T||=1.933e-143
k=  310 ||T||=3.273e-148
k=  320 ||T||=5.543e-153
k=  330 ||T||=9.387e-158
k=  340 ||T||=0.000e+00


## M-matrices

In the following section, you'll "verify" some M-matrix properties, experimentally. 

For this, please form your own $4 \times 4$ M-matrix. Do this by picking a suitable  $B \geq 0$, and then apply Gerschgorin's Theorem to pick a $s > \rho(B)$. 

Finally, set $A=sI - B$.

### Exercise 
#### An example 
Make up your own M-matrix, as per the previous cell, and check it is inverse non-negative.

In [31]:
B = np.array([
    [1, 1, 1, 0],
    [1, 2, 1, 1],
    [0, 1, 3, 2],
    [0, 1, 2, 2]
])
s = 6

In [32]:
A = s*np.eye(4)-B
print(A)

[[ 5. -1. -1.  0.]
 [-1.  4. -1. -1.]
 [ 0. -1.  3. -2.]
 [ 0. -1. -2.  4.]]


In [33]:
print(inv(A))

[[0.23076923 0.15384615 0.23076923 0.15384615]
 [0.08791209 0.43956044 0.37362637 0.2967033 ]
 [0.06593407 0.32967033 0.78021978 0.47252747]
 [0.05494505 0.27472527 0.48351648 0.56043956]]


### Principal submatrices minors

Given a matrix $A$.
* $B$ is a _submatrix_ of $A$ if it can be obtained by deleting some rows and columns of $A$
* $B$ is a _principle submatrix_ of $A$ if it can be obtained by deleting some rows of $A$ and the _corresponding_ columns of $A$. E.g., if you delete row 1 of $A$ you also delete column $1$.
* $B$ is a _leading principle submatrix_ of order $k$ of $A$ if, in Python notation, `B=A[0:k+1,0:k+1]`. We denote it $B=A^{(k)}$

The Principal Minors of $A$ are the determinants of the $A^{(k)}$

#### Exercises

Verify that the Principla Minors of you M-matrix, $A$ are all positive.

In [44]:
for k in range(5):
    Ak = A[0:k,0:k]
    print(f"k={k:d}, det(Ak)={det(Ak):.3f}")

k=0, det(Ak)=1.000
k=1, det(Ak)=5.000
k=2, det(Ak)=19.000
k=3, det(Ak)=51.000
k=4, det(Ak)=91.000


## SPD matrices

The simplest way of making up an SPD matrix to to choose any invertible matrix $C$, and set $A=C^T C$.

Example (and note the use of `.T` for transpose and `@` for matrix multiplicaiton.

In [62]:
C= np.array([
    [2, -1],
    [-2, 0]
])
A = C.T @ C
print(A)

[[ 8 -2]
 [-2  1]]


We know that $A$ SPD *if and only if* $A=A^T$ and all the eigenvalues of $A$ are positive.
Let's check:

In [58]:
print(f"Check A=A^T: {norm(A-A.T)==0}")

Check A=A^T: True


In [63]:
l = eigvals(A)
for lambda_k in l:
    print(lambda_k)

8.531128874149275
0.4688711258507251


### Exerise
Make up a $4 \times 4$ SPD matrix and check that it is SPD.

### Exercise
Verify that all the leading principal submatrices of your example are SPD

## To finish

If you are doing assessment for the summer school send your completed notebook to Niall (mailto:Niall.Madden@UniversityOfGalway.ie), in either PDF or HTML formats.


## Part 2:
* Send Niall written solutions to the following Questions (to be added later!)